# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 04:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_referer', models.CharField(max_length=128, null=True, verbose_name='HTTP Referer')),
                ('http_user_agent', models.TextField(null=True, verbose_name='HTTP User Agent')),
                ('remote_addr', models.CharField(max_length=40, verbose_name='Remote Address')),
                ('request_method', models.CharField(max_length=8, verbose_name='Request Method')),
                ('path', models.CharField(max_length=256, verbose_name='Path')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('content', models.CharField(max_length=128, verbose_name='Content')),
                ('latitude', models.FloatField(default=0, verbose_name='Latitude')),
                ('longitude', models.FloatField(default=0, verbose_name='Longitude')),
                ('country', models.CharField(blank=True, max_length=2, verbose_name='Country')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
