# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=32, verbose_name='Country')),
                ('country_code', models.CharField(blank=True, max_length=2, verbose_name='Country Code')),
                ('region', models.CharField(blank=True, max_length=32, verbose_name='Region')),
                ('region_code', models.CharField(blank=True, max_length=8, verbose_name='Region Code')),
                ('city', models.CharField(blank=True, max_length=32, verbose_name='City')),
                ('zip_code', models.CharField(blank=True, max_length=8, verbose_name='Zip Code')),
                ('latitude', models.FloatField(default=0, verbose_name='Latitude')),
                ('longitude', models.FloatField(default=0, verbose_name='Longitude')),
                ('timezone', models.CharField(blank=True, max_length=32, verbose_name='Timezone')),
                ('isp', models.CharField(blank=True, max_length=32, verbose_name='ISP')),
                ('organization', models.CharField(blank=True, max_length=32, verbose_name='Organiztion')),
                ('as_name', models.CharField(blank=True, max_length=32, verbose_name='AS number/name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='country',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='longitude',
        ),
        migrations.AddField(
            model_name='entry',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_logger.Location', verbose_name='Location'),
        ),
    ]
