# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='http_referer',
            field=models.CharField(max_length=512, null=True, verbose_name='HTTP Referer'),
        ),
    ]
