# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logger', '0003_entry_remote_addr_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_secure',
            field=models.BooleanField(default=False, verbose_name='Is Secure'),
        ),
    ]
