# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logger', '0004_entry_is_secure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='content',
            new_name='description'
        ),
    ]
