# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logger', '0005_renamed_entry_content_to_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Description'),
        ),
    ]
