# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logger', '0006_auto_20160421_2357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('-created',), 'verbose_name_plural': 'entries'},
        ),
    ]
