# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logger', '0007_auto_20160422_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
            ],
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='path',
            new_name='deprecated_path',
        ),
    ]
