# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def fix_paths(apps,schema_editor):
    """
    Copy the information from the Entry.path to a Path.name and reference the new
    instance from Entry.path_name to Path
    """
    Entry = apps.get_model("activity_logger", "Entry")
    Path = apps.get_model("activity_logger", "Path")

    entries = Entry.objects.all()
    for entry in entries:
        try:
            path = Path.objects.get(name=entry.deprecated_path)
        except Entry.DoesNotExist,__fake__.DoesNotExist:
            path = Path(name=entry.deprecated_path).save()
        entry.path_name = path
        entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logger', '0008_auto_20160423_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='path',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_logger.Path', verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='deprecated_path',
            field=models.CharField(max_length=256, null=True, verbose_name='Path'),
        ),
        migrations.RunPython(fix_paths),
    ]
