# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logger', '0010_fix_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_logger.Path', verbose_name='Path'),
        ),
    ]
