# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logger', '0011_auto_20160423_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='deprecated_path',
        ),
    ]
